# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bplant.proto\"\x1d\n\x0cPlantRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"7\n\rPlantResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32?\n\x0cPlantService\x12/\n\x0ePredictDisease\x12\r.PlantRequest\x1a\x0e.PlantResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANTREQUEST']._serialized_start=15
  _globals['_PLANTREQUEST']._serialized_end=44
  _globals['_PLANTRESPONSE']._serialized_start=46
  _globals['_PLANTRESPONSE']._serialized_end=101
  _globals['_PLANTSERVICE']._serialized_start=103
  _globals['_PLANTSERVICE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
