# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import plant_pb2 as plant__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlantServiceStub(object):
    """hadi kandiro fiha function li hatakhud req ou t3ti repo
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictDisease = channel.unary_unary(
                '/PlantService/PredictDisease',
                request_serializer=plant__pb2.PlantRequest.SerializeToString,
                response_deserializer=plant__pb2.PlantResponse.FromString,
                _registered_method=True)


class PlantServiceServicer(object):
    """hadi kandiro fiha function li hatakhud req ou t3ti repo
    """

    def PredictDisease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictDisease': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictDisease,
                    request_deserializer=plant__pb2.PlantRequest.FromString,
                    response_serializer=plant__pb2.PlantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PlantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PlantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlantService(object):
    """hadi kandiro fiha function li hatakhud req ou t3ti repo
    """

    @staticmethod
    def PredictDisease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PlantService/PredictDisease',
            plant__pb2.PlantRequest.SerializeToString,
            plant__pb2.PlantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
