# Generated by Django 5.2.8 on 2026-04-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at']},
        ),
    ]
