# Generated by Django 5.2.8 on 2026-04-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_history_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'History'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay',
            field=models.CharField(default='0', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ville',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='City'),
        ),
    ]
